package com.techRestore.tech.restore.common.model.enums;

public enum NotificationType {
    ORDER_PLACED,
    ORDER_CONFIRMED,
    ORDER_PROCESSING,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    REPAIR_REQUESTED,
    REPAIR_QUOTE_SENT,
    REPAIR_QUOTE_APPROVED,
    REPAIR_COMPLETED,
    REPAIR_DEVICE_DELIVERED
}